Submit Tamagotchi 01 assignment
gear-foundation/dapps-template-gear-academy pull request #8
Opened 2023-09-03 11:19 UTC by Retamogordo

2023-09-04 08:06 UTC, shamilsan requested changes
You are to:

- [X] Fork this repo.
- [ ] Rename it according to the rules: https://academy.gear.rs/getting-started/homework-rules
- [ ] Enable GitHub actions for it.
- [ ] Create a PR for your repo, but not for this one.

2023-09-04 08:06 UTC, shamilsan commented on frontend/yarn.lock
Unnecessary changes.

2023-09-04 08:06 UTC, shamilsan commented on .github/workflows/jekyll-gh-pages.yml
What this file is for?

2023-09-04 08:06 UTC, shamilsan commented on 01-tamagotchi/src/lib.rs
> +        TmgAction::Age => msg::reply(exec::block_timestamp() - tmg.date_of_birth, 0),
Need to reply with `TmgEvent` enum here.

2023-09-04 22:43 UTC, Retamogordo commented
Hi Shamil,
thank you for your feedback and sorry for the mess.

I'll try to fix it.

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Sep 4, 2023, 05:06 by ***@***.***:

>
>
>
>
> @shamilsan>  requested changes on this pull request.
>
>
> You are to:
>
> Fork this repo.
> Rename it according to the rules: > https://academy.gear.rs/getting-started/homework-rules
> Enable GitHub actions for it.
> Create a PR for your repo, but not for this one.
>
>
>
> In > 01-tamagotchi/src/lib.rs <https://github.com/gear-foundation/dapps-template-gear-academy/pull/8#discussion_r1314568805>> :
>
> >  }  #[no_mangle] extern "C" fn state() {-    // TODO: 7️⃣ Return the Tamagotchi state+    msg::reply(unsafe { TAMAGOTCHI.clone().unwrap() }, 0).expect("Unable to return Tamagotchi instance");
>
> No need to clone. You can > take>  it of send the reply by reference.
>
>
>
>
> In > 01-tamagotchi/src/lib.rs <https://github.com/gear-foundation/dapps-template-gear-academy/pull/8#discussion_r1314570645>> :
>
> >  }  #[no_mangle] extern "C" fn handle() {-    // TODO: 6️⃣ Add handling of `Name` and `Age` actions+    let action: TmgAction = msg::load().expect("Error in loading Tamagotchi Action");+    let tmg = unsafe { TAMAGOTCHI.as_ref().unwrap() };++    let _ = match action {
>
> Better would be handle > Result>  from > mag::reply> . At least, add an > expect> .
>
>
>
>
> On > frontend/yarn.lock <https://github.com/gear-foundation/dapps-template-gear-academy/pull/8#discussion_r1314572755>> :
>
>
> Unnecessary changes.
>
>
>
>
> On > .github/workflows/jekyll-gh-pages.yml <https://github.com/gear-foundation/dapps-template-gear-academy/pull/8#discussion_r1314573396>> :
>
>
> What this file is for?
>
>
>
>
> In > 01-tamagotchi/src/lib.rs <https://github.com/gear-foundation/dapps-template-gear-academy/pull/8#discussion_r1314575238>> :
>
> > +        TmgAction::Name => msg::reply(tmg.name.clone(), 0),+        TmgAction::Age => msg::reply(exec::block_timestamp() - tmg.date_of_birth, 0),
>
> Need to reply with > TmgEvent>  enum here.
>
>
>
> —
> Reply to this email directly, > view it on GitHub <https://github.com/gear-foundation/dapps-template-gear-academy/pull/8#pullrequestreview-1608969094>> , or > unsubscribe <https://github.com/notifications/unsubscribe-auth/ANRCKG4TGAZCR7ZVNXN7ABTXYWDY5ANCNFSM6AAAAAA4JH4HTU>> .
> You are receiving this because you authored the thread.> Message ID: > <gear-foundation/dapps-template-gear-academy/pull/8/review/1608969094> @> github> .> com>
>
>
>

2023-09-05 07:33 UTC, shamilsan commented
Hi,
So I am waiting for your PR at https://github.com/Retamogordo/yuryy-gear-academy

Closing this PR.

2023-09-05 07:33 UTC, closed without merging